# attogram/router - codeclimate checks
version: "2"
exclude_patterns:
- "vendor/"
checks:
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 22
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false # allow $GLOBALS in getGlobal()
  phan:
    enabled: true
    checks:
      PhanTypeMismatchArgument:
        enabled: false
      PhanTypeMismatchForeach:
        enabled: false       
      PhanTypeMismatchProperty:
        enabled: false
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredInterface:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 41
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
