# Attogram Router - https://github.com/attogram/router
# codeclimate checks - https://codeclimate.com/github/attogram/router
#
version: "2"
exclude_patterns:
- "vendor/"
checks:
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      ExcessiveClassComplexity:
        maximum: 55
    checks:
      Controversial/Superglobals:
        enabled: false # allow $GLOBALS in getGlobal(), $_SERVER in __construct()
  phan:
    enabled: true
    checks:
      PhanTypeMismatchArgument:
        enabled: false
      PhanTypeMismatchForeach:
        enabled: false       
      PhanTypeMismatchProperty:
        enabled: false
      PhanUndeclaredClass:
        enabled: false
      PhanUndeclaredClassCatch:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUndeclaredInterface:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
      PhanNoopVariable:
        enabled: false # allow unused $_SERVER; when needed to override auto_globals_jit
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 41
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
