# Attogram Router - https://github.com/attogram/router
# codeclimate checks - https://codeclimate.com/github/attogram/router
#
version: "2"
exclude_patterns:
- "vendor/"
checks:
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false # allow $GLOBALS in getGlobal(), $_SERVER in __construct()
      Design/ExitExpression:
        enabled: false # allow exit in redirect()
  phan:
    enabled: true
    checks:
      PhanNoopVariable:
        enabled: false # allow unused $_SERVER; when needed to override auto_globals_jit
  sonar-php:
    enabled: true
    config:
      minimum_severity: major # info, minor, major (default), critical, blocker
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 41
  csslint:
    enabled: true
  stylelint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
