# attogram/router - .travis.yml - v0.0.2

language: php

php:
  - 7.0
  - 7.1
  - 7.2
#  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install
  
script:
  - if find src/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find tests/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find vendor/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
