# Attogram Router - https://github.com/attogram/router
# Travis CI - https://travis-ci.org/attogram/router
#

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  
matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - if find examples/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find src/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find tests/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - if find vendor/ -name "*.php" -exec php -l {} 2>&1 \; | grep "error,"; then exit 1; fi;
  - phpunit tests/RouterTest.php
